project_name: network_go

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/main.go
    ldflags: -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
checksum:
  name_template: '{{ .ProjectName }}-{{.Version}}_checksums.txt'
changelog:
  skip: true

archives:
  - format: binary
    replacements:
      darwin: macOS
    name_template:
