// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // |
			nil,      // &
			shift(4), // bucket
			nil,      // operator
			nil,      // matter
			shift(5), // (
			nil,      // )
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // |
			nil,          // &
			nil,          // bucket
			nil,          // operator
			nil,          // matter
			nil,          // (
			nil,          // )
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Query
			shift(8),  // |
			shift(9),  // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: FieldQuery
			reduce(8), // |, reduce: FieldQuery
			reduce(8), // &, reduce: FieldQuery
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			shift(10), // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			shift(14), // bucket
			nil,       // operator
			nil,       // matter
			shift(15), // (
			nil,       // )
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Query
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Query
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // |
			nil,      // &
			shift(4), // bucket
			nil,      // operator
			nil,      // matter
			shift(5), // (
			nil,      // )
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // |
			nil,      // &
			shift(4), // bucket
			nil,      // operator
			nil,      // matter
			shift(5), // (
			nil,      // )
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			shift(18), // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			shift(19), // )
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // |
			shift(23), // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(3), // ), reduce: Query
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // |, reduce: FieldQuery
			reduce(8), // &, reduce: FieldQuery
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(8), // ), reduce: FieldQuery
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			shift(24), // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			shift(14), // bucket
			nil,       // operator
			nil,       // matter
			shift(15), // (
			nil,       // )
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: OrQuery
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: AndQuery
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Field
			reduce(6), // |, reduce: Field
			reduce(6), // &, reduce: Field
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: FieldQuery
			reduce(7), // |, reduce: FieldQuery
			reduce(7), // &, reduce: FieldQuery
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(1), // ), reduce: Query
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(2), // ), reduce: Query
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			shift(14), // bucket
			nil,       // operator
			nil,       // matter
			shift(15), // (
			nil,       // )
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			shift(14), // bucket
			nil,       // operator
			nil,       // matter
			shift(15), // (
			nil,       // )
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			shift(28), // matter
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			shift(29), // )
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(4), // ), reduce: OrQuery
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // |
			nil,       // &
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(5), // ), reduce: AndQuery
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // |, reduce: Field
			reduce(6), // &, reduce: Field
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(6), // ), reduce: Field
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // |, reduce: FieldQuery
			reduce(7), // &, reduce: FieldQuery
			nil,       // bucket
			nil,       // operator
			nil,       // matter
			nil,       // (
			reduce(7), // ), reduce: FieldQuery
		},
	},
}
