// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 6

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Query
		-1, // OrQuery
		-1, // AndQuery
		3,  // Field
		2,  // FieldQuery
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Query
		7,  // OrQuery
		6,  // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S5
		-1, // S'
		11, // Query
		-1, // OrQuery
		-1, // AndQuery
		13, // Field
		12, // FieldQuery
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S8
		-1, // S'
		16, // Query
		-1, // OrQuery
		-1, // AndQuery
		3,  // Field
		2,  // FieldQuery
	},
	gotoRow{ // S9
		-1, // S'
		17, // Query
		-1, // OrQuery
		-1, // AndQuery
		3,  // Field
		2,  // FieldQuery
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Query
		21, // OrQuery
		20, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S15
		-1, // S'
		25, // Query
		-1, // OrQuery
		-1, // AndQuery
		13, // Field
		12, // FieldQuery
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S22
		-1, // S'
		26, // Query
		-1, // OrQuery
		-1, // AndQuery
		13, // Field
		12, // FieldQuery
	},
	gotoRow{ // S23
		-1, // S'
		27, // Query
		-1, // OrQuery
		-1, // AndQuery
		13, // Field
		12, // FieldQuery
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Query
		-1, // OrQuery
		-1, // AndQuery
		-1, // Field
		-1, // FieldQuery
	},
}
